# Generated by Django 5.2.5 on 2025-10-06 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='data_adicao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
    ]
