# Generated by Django 5.2.5 on 2025-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_entrega_data_adicao_entrega_data_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('entregas', models.ManyToManyField(related_name='rotas', to='rotas.entrega')),
            ],
        ),
    ]
